name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - name: Hent variabel fra secrets
      run: |
        echo "dette er en test"
    
    - uses: actions/checkout@v2
    
    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'
        msbuild-architecture: x64
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Create install folder
      run: mkdir ${{ secrets.INSTALL_FOLDER }}
      
    - name: Navigate to Install folder
      run: cd mkdir ${{ secrets.INSTALL_FOLDER }}      

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
           msbuild.exe Sandbox.sln /p:platform="Any CPU" /p:configuration="Release"

