name: .NET publish Windows 2016 

on: 
  push:
    branches: [ master ]

jobs:
  build:
    environment: test
    runs-on: [self-hosted, windows, x64]
  
    steps:
    - name: Hent variabel fra secrets
      run: |
        echo ${{ secrets.REPO_SECRET }}
    
    - uses: actions/checkout@v2
    
    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'
        msbuild-architecture: x64
    
    # - name: Setup MSBuild
    #   uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Create install folder
      run: |
          # $Folder = ${{ secrets.INSTALL_FOLDER }}
          $Folder = 'test'
          if (Test-Path -Path ('C:\inetpub\wwwroot\'+$Folder)) {
            echo 'katalog eksisterer fra før'
            Remove-Item -LiteralPath ('C:\inetpub\wwwroot\'+$Folder) -Force -Recurse
            new-item -Path 'C:\inetpub\wwwroot\' -Name $Folder -ItemType "directory"
          } 
          else {
            echo 'katalog eksisterer ikke'
            new-item -Path 'C:\inetpub\wwwroot\' -Name $Folder -ItemType "directory"
          }
      
    - name: Navigate to Install folder
      run: cd ${{ secrets.INSTALL_FOLDER }}      

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
           msbuild.exe Sandbox.sln /p:platform="Any CPU" /p:configuration="Release"

