name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'  
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE      

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
           msbuild.exe Sandbox.sln /p:platform="Any CPU" /p:configuration="Release"

